#!/usr/bin/env bash
set -euo pipefail

usage() { echo "Usage: configure.sh --project-root DIR [--install-tools] [--download-models] [--whisper-model FILE] [--vad-model FILE]"; }
PROJECT_ROOT=""; INSTALL_TOOLS=0; DOWNLOAD_MODELS=0; WHISPER_MODEL_SOURCE=""; VAD_MODEL_SOURCE=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --project-root) PROJECT_ROOT=${2:?}; shift 2 ;;
    --install-tools) INSTALL_TOOLS=1; shift ;;
    --download-models) DOWNLOAD_MODELS=1; shift ;;
    --whisper-model) WHISPER_MODEL_SOURCE=${2:?}; shift 2 ;;
    --vad-model) VAD_MODEL_SOURCE=${2:?}; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done
[ -n "$PROJECT_ROOT" ] || { usage >&2; exit 2; }
PROJECT_ROOT=$(cd "$PROJECT_ROOT" && pwd -P)
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd -P)
SKILL_DIR=$(cd "$SCRIPT_DIR/../.." && pwd -P)
MODEL_CONFIG=${MIRA_MODEL_CONFIG:-"$SKILL_DIR/config/model-config.env"}
[ -f "$MODEL_CONFIG" ] || { echo "Model configuration not found: $MODEL_CONFIG" >&2; exit 1; }

for variable in WHISPER_MODEL_NAME WHISPER_MODEL_FILE WHISPER_MODEL_URL WHISPER_MODEL_SIZE VAD_MODEL_NAME VAD_MODEL_FILE VAD_MODEL_URL VAD_MODEL_SIZE; do eval "CALLER_${variable}=\${$variable-}"; done
# shellcheck disable=SC1090
. "$MODEL_CONFIG"
for variable in WHISPER_MODEL_NAME WHISPER_MODEL_FILE WHISPER_MODEL_URL WHISPER_MODEL_SIZE VAD_MODEL_NAME VAD_MODEL_FILE VAD_MODEL_URL VAD_MODEL_SIZE; do
  eval "caller_value=\${CALLER_${variable}}"; [ -z "$caller_value" ] || eval "$variable=\$caller_value"; eval ": \"\${$variable:?Missing $variable}\""
done

MODELS_DIR="$PROJECT_ROOT/interview-artifacts/models"
CONFIG_DIR="$PROJECT_ROOT/.mira-interview"
CONFIG_FILE="$CONFIG_DIR/config.env"
find_command() { command -v "$1" 2>/dev/null || true; }
FFMPEG_BIN=$(find_command ffmpeg); WHISPER_BIN=$(find_command whisper-cli)
if [ "$INSTALL_TOOLS" -eq 1 ] && { [ -z "$FFMPEG_BIN" ] || [ -z "$WHISPER_BIN" ]; }; then
  BREW_BIN=$(find_command brew); [ -n "$BREW_BIN" ] || { echo "Homebrew is required." >&2; exit 1; }
  [ -n "$FFMPEG_BIN" ] || "$BREW_BIN" install ffmpeg
  [ -n "$WHISPER_BIN" ] || "$BREW_BIN" install whisper-cpp
  FFMPEG_BIN=$(find_command ffmpeg); WHISPER_BIN=$(find_command whisper-cli)
fi
[ -n "$FFMPEG_BIN" ] || { echo "ffmpeg not found." >&2; exit 1; }
[ -n "$WHISPER_BIN" ] || { echo "whisper-cli not found." >&2; exit 1; }
/bin/mkdir -p "$MODELS_DIR" "$CONFIG_DIR"

stage_existing_model() {
  source_path=$1; destination=$2
  [ -s "$source_path" ] || { echo "Model not found: $source_path" >&2; return 1; }
  source_dir=$(cd "$(dirname "$source_path")" && pwd -P); source_path="$source_dir/$(basename "$source_path")"
  [ "$source_path" = "$destination" ] && return
  if [ -e "$destination" ] || [ -L "$destination" ]; then
    [ -L "$destination" ] && [ "$(readlink "$destination")" = "$source_path" ] && return
    echo "Model destination already exists: $destination" >&2; return 1
  fi
  /bin/ln -s "$source_path" "$destination"
}
WHISPER_MODEL="$MODELS_DIR/$WHISPER_MODEL_FILE"; VAD_MODEL="$MODELS_DIR/$VAD_MODEL_FILE"
[ -z "$WHISPER_MODEL_SOURCE" ] || stage_existing_model "$WHISPER_MODEL_SOURCE" "$WHISPER_MODEL"
[ -z "$VAD_MODEL_SOURCE" ] || stage_existing_model "$VAD_MODEL_SOURCE" "$VAD_MODEL"
if [ "$DOWNLOAD_MODELS" -eq 1 ]; then
  CURL_BIN=$(find_command curl); [ -n "$CURL_BIN" ] || { echo "curl not found." >&2; exit 1; }
  echo "Whisper model: $WHISPER_MODEL_NAME ($WHISPER_MODEL_SIZE)"; echo "VAD model: $VAD_MODEL_NAME ($VAD_MODEL_SIZE)"
  [ -s "$WHISPER_MODEL" ] || "$CURL_BIN" -L --fail --retry 3 --continue-at - -o "$WHISPER_MODEL" "$WHISPER_MODEL_URL"
  [ -s "$VAD_MODEL" ] || "$CURL_BIN" -L --fail --retry 3 --continue-at - -o "$VAD_MODEL" "$VAD_MODEL_URL"
fi
[ -s "$WHISPER_MODEL" ] || { echo "Whisper model not found: $WHISPER_MODEL" >&2; exit 1; }
[ -s "$VAD_MODEL" ] || { echo "VAD model not found: $VAD_MODEL" >&2; exit 1; }
quote_env() { printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"; }
{
  echo "# Generated by mira-interview. Load only when this project is trusted."
  printf 'FFMPEG_BIN=%s\n' "$(quote_env "$FFMPEG_BIN")"
  printf 'WHISPER_BIN=%s\n' "$(quote_env "$WHISPER_BIN")"
  printf 'WHISPER_MODEL_NAME=%s\n' "$(quote_env "$WHISPER_MODEL_NAME")"
  printf 'WHISPER_MODEL=%s\n' "$(quote_env "$WHISPER_MODEL")"
  printf 'VAD_MODEL=%s\n' "$(quote_env "$VAD_MODEL")"
  printf 'TRANSCRIPTION_PROMPT=%s\n' "$(quote_env "这是一场只有两位参与者的求职面试对话：一位面试官，一位候选人（面试者）。请按实际发言完整转录对话。")"
  echo "WHISPER_THREADS=8"
} > "$CONFIG_FILE"
echo "Configuration ready: $CONFIG_FILE"
